version: '3.8'
services:

  php-apache-environment:
    container_name: php-apache
    image: php:8.1-apache
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/
    ports:
      - 8000:80